/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.brayanlolv.jogoforca.templates;

/**
 *
 * @author braya
 */
public class EndScreen extends javax.swing.JInternalFrame {

    /**
     * Creates new form endScreen
     */
    
    public EndScreen(boolean win,String rightWord) {
    
        initComponents();
        if(win){
            menssage.setText("vitoria");
            menssage.setForeground(new java.awt.Color(0,153, 51));
        }
        
        rightWordLbl.setText("Palavra: "+ rightWord);
    }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menssage = new javax.swing.JLabel();
        rightWordLbl = new javax.swing.JLabel();

        setForeground(java.awt.Color.white);
        setVisible(true);

        menssage.setBackground(new java.awt.Color(255, 255, 255));
        menssage.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        menssage.setForeground(new java.awt.Color(204, 0, 0));
        menssage.setText("Derrota");

        rightWordLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rightWordLbl.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(rightWordLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(menssage, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(169, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menssage, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rightWordLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 126, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel menssage;
    private javax.swing.JLabel rightWordLbl;
    // End of variables declaration//GEN-END:variables
}
