    /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.brayanlolv.jogoforca.templates;
import com.brayanlolv.jogoforca.templates.*;
import com.brayanlolv.jogoforca.Jogo;
import javax.swing.JLabel;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.JDialog;
import java.awt.image.BufferedImage;

/**
 *
 * @author braya
 */
public class JogoTela extends javax.swing.JInternalFrame {

    /**
     * Creates new form JogoTela
     */
    
    Jogo jogo;
    JPanel mainPanel;
 

    
    public JogoTela(Jogo receivedJogo, JPanel panel) {
        jogo = receivedJogo;
        initComponents();
        jogo.view();
        mainPanel = panel;
        this.render();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        palavra = new javax.swing.JLabel();
        inputLetter = new javax.swing.JButton();
        letterIpt = new javax.swing.JTextField();
        tryWordBtn = new javax.swing.JButton();
        tryWordIpt = new javax.swing.JTextField();
        man = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        tryiedWordLbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        palavra.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        palavra.setText("teste");

        inputLetter.setText("tentar letra");
        inputLetter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputLetterActionPerformed(evt);
            }
        });

        tryWordBtn.setText("tentar palavra");
        tryWordBtn.setToolTipText("");
        tryWordBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tryWordBtnActionPerformed(evt);
            }
        });

        tryWordIpt.setToolTipText("");

        man.setText("jLabel1");

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tryiedWordLbl.setText("jLabel1");

        jLabel1.setText("letras entradas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tryWordIpt, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                            .addComponent(letterIpt))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tryWordBtn)
                            .addComponent(inputLetter, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(96, 96, 96)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(tryiedWordLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(palavra, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(man))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jButton1)))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tryiedWordLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(palavra)
                            .addComponent(man))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(letterIpt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputLetter))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tryWordIpt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tryWordBtn))
                        .addGap(59, 59, 59)
                        .addComponent(jButton1)))
                .addContainerGap(170, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputLetterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputLetterActionPerformed
       String letterIptText = letterIpt.getText();
       if(letterIptText.length() > 0){
        
           char letter = letterIptText.charAt(0);
           System.out.println(letter);
           int action = jogo.enterChar(letter);
           if(action == 2){
               
               //chamar a tela para tentar uma palavra
           }
           this.render();
           
            
       }
//jogo.enterChar('l');
        //jogo.enterChar(letterIptText.charAt(0));
            
//int happen = jogo.enterChar('a');
      //  this.render();
  // TODO add your handling code here:
    }//GEN-LAST:event_inputLetterActionPerformed

    private void tryWordBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tryWordBtnActionPerformed
       String triedWord =  tryWordIpt.getText();
        
        if(!triedWord.equals("")){
          if(jogo.tryWord(triedWord)){
            //charmar tela de vitoria
            endWindow(true);
        }
          else{
              //chamar tela de vitoria
              endWindow(false);
                  }
        }
        
        jogo.tryWord(triedWord);
    
// TODO add your handling code here:
    }//GEN-LAST:event_tryWordBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        endWindow(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void endWindow(boolean won){

        EndScreen wonFrame = new EndScreen(won,jogo.targetWord);
        mainPanel.remove(this);
        mainPanel.add(wonFrame);
        wonFrame.setVisible(true);
        this.setVisible(false);
        jogo = null;
        mainPanel = null;
         System.gc();
       
   
    }
    
    //menu call
        //
    
    private void render(){
       
      int imgIndex =  5 - jogo.tries ;  
      if(imgIndex < 0 ){
          imgIndex = 5;
      }
      
      tryiedWordLbl.setText(jogo.enteredChars.toString());
      
        
      man.setIcon(new ImageIcon("src\\main\\java\\com\\brayanlolv\\jogoforca\\templates\\imgs\\"+imgIndex +".png"));
      palavra.setText(jogo.getWord());
      System.out.println("objetivo " + jogo.targetWord);
      System.out.println("o q vai mostrar é " + jogo.getWord());
      letterIpt.setText("");
      man.setText(String.valueOf(jogo.tries));
      validate();
        /* for(int i = 0; i < jogo.getWord().length();i++){;
           JLabel teste = new JLabel();
           teste.setText("_");
           targetWordPanel.add(teste);
          
       }*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton inputLetter;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField letterIpt;
    private javax.swing.JLabel man;
    private javax.swing.JLabel palavra;
    private javax.swing.JButton tryWordBtn;
    private javax.swing.JTextField tryWordIpt;
    private javax.swing.JLabel tryiedWordLbl;
    // End of variables declaration//GEN-END:variables
}
