/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.brayanlolv.jogoforca.templates;
import com.brayanlolv.jogoforca.templates.JogoTela;
import com.brayanlolv.jogoforca.templates.MainDisplay;
import javax.swing.JPanel;
import com.brayanlolv.jogoforca.Jogo;
/**
 *
 * @author braya
 */
public class Menu extends javax.swing.JInternalFrame {

    /**
     * Creates new form Menu
     */
   JPanel panel;
    public Menu(JPanel panel) {
        this.panel = panel;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        seedBtn = new javax.swing.JButton();
        seedIpt = new javax.swing.JTextField();

        jButton1.setText("aleatorio");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        seedBtn.setText("seed ");
        seedBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seedBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seedBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seedIpt, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(229, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(seedBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(seedIpt, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void seedBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seedBtnActionPerformed
            System.out.println("botao apertado");
        //Jogo jogo = new Jogo(Integer.parseInt(seedIpt.getText()));//mudar
        JogoTela jogoTela = new JogoTela(new Jogo(Integer.parseInt(seedIpt.getText())), panel);
       
        panel.removeAll();
         this.setVisible(false);
        panel.add(jogoTela);
        jogoTela.setVisible(true);
         panel = null;
         System.gc();
        // TODO add your handling code here:
    }//GEN-LAST:event_seedBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.out.println("botao apertado");
        Jogo jogo = new Jogo();
        JogoTela jogoTela = new JogoTela(jogo, panel);
       
        panel.removeAll();
         this.setVisible(false);
        panel.add(jogoTela);
        jogoTela.setVisible(true);
         panel = null;
           System.gc();
        //JogoTela jogoTela = new JogoTela();
        //this.add(jogoTela);
        //jogoTela.setVisible(true);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton seedBtn;
    private javax.swing.JTextField seedIpt;
    // End of variables declaration//GEN-END:variables
}
